#!/bin/bash
# Problem 3: Synthesizing Chemical Reaction Networks

echo "=============================================="
echo "Problem 3(a): Z = X * log2(Y)"
echo "  X = 5, Y = 16"
echo "  Expected: Z = 5 * log2(16) = 5 * 4 = 20"
echo ""
echo "  CRN Design (integrated log-multiply module):"
echo "    b  -> a1 + b         (slow: drive iterations)"
echo "    a1 + 2Y -> c + Yp + a1  (fastest: halve Y)"
echo "    2c -> c              (fastest: reduce c to 1)"
echo "    a1 -> W1             (fast: a1 decays)"
echo "    c + X -> c + Xp + Z (medium: copy X into Z)"
echo "    c  -> W2             (slower: c decays after copying)"
echo "    Xp -> X              (slow: restore X)"
echo "    Yp -> Y              (slow: restore Y for next halving)"
echo ""
echo "  Each halving iteration produces 1 c molecule."
echo "  That c copies X molecules into Z, then decays."
echo "  After log2(Y) halvings, Z = X * log2(Y)."
echo "=============================================="
echo ""
./aleae p3a.in p3a.r 1000 100 0
echo ""
echo "(Look at the 'Z' row -- its mean should be close to 20)"

echo ""
echo ""
echo "=============================================="
echo "Problem 3(b): Y = 2^(log2(X))"
echo "  X = 8"
echo "  Expected: Y = 2^(log2(8)) = 2^3 = 8"
echo ""
echo "  CRN Design (chained log + exp modules):"
echo "  Log module (computes L = log2(X)):"
echo "    b  -> a1 + b         (slow: drive iterations)"
echo "    a1 + 2X -> c + Xp + a1  (fastest: halve X)"
echo "    2c -> c              (fastest: reduce c to 1)"
echo "    a1 -> W1             (fast: a1 decays)"
echo "    Xp -> X              (medium: restore X)"
echo "    c  -> L              (medium: output 1 per halving)"
echo ""
echo "  Exp module (computes Y = 2^L):"
echo "    L  -> a2             (very slow: consume L)"
echo "    a2 + Y -> a2 + 2Yp  (fastest: double Y)"
echo "    a2 -> W2             (fast: a2 decays)"
echo "    Yp -> Y              (medium: restore Y)"
echo ""
echo "  Y starts at 1. Each L consumed doubles Y."
echo "  After all L consumed: Y = 2^L = 2^(log2(X)) = X."
echo "=============================================="
echo ""
./aleae p3b.in p3b.r 1000 500 0
echo ""
echo "(Look at the 'Y' row -- its mean should be close to 8)"
